{% set name = "mudata" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mudata-{{ version }}.tar.gz
  sha256: b1456bc4053aa48a88ba8965440546efa98be6550dbf29a13eeec193cbf1d24e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core
    - pip
    - python >=3.6
  run:
    - anndata >=0.8
    - xlrd <2.0
    - h5py
    - numpy
    - pandas
    - python >=3.6

test:
  imports:
    - mudata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scverse/mudata
  summary: Multimodal annotated datasets
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gtca
